blog/urls.py
from django.urls import path
from . import views


urlpatterns = [  

    path('', views.blogs, name="blog"),
    path('categoria/<int:categoria_id>/', views.categoria, name="categoria"),
]

carro/urls.py
from django.urls import path

from .import views

app_name= "carro"

urlpatterns = [
   
   
    path("agregar/<int:producto_id>/", views.agregar_producto, name="agregar"),
    path("eliminar/<int:producto_id>/", views.eliminar_producto, name="eliminar"),
    path("restar/<int:producto_id>/", views.restar_producto, name="restar"),
    path("limpiar/", views.limpiar_carro, name="limpiar"),
   
    
]

proyectoweb/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('proyectowebapp.urls')),
    path('servicios/', include('servicios.urls')),
    path('blog/', include('blog.urls')),
    path('contacto/', include('contacto.urls')),
    path('tienda/', include('tienda.urls')),
    path('carro/', include('carro.urls')),
    path('paraelcolaborador/', include('paraelcolaborador.urls')),
    path('autenticacion/', include('autenticacion.urls')),
    path('pedidos/', include('pedidos.urls')),
    

]

tienda/urls.py
from django.urls import path
from . import views


urlpatterns = [
  
    
    path('', views.tienda, name="Tienda"),
    
]

tienda/models.py
from django.db import models

# Create your models here.
class categoriaProd(models.Model):
    nombre=models.CharField(max_length=50)
    created=models.DateTimeField(auto_now_add=True)
    update=models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name="CategoriaProd"
        verbose_name_plural="CategoriasProd"

    def __str__(self):
        return (self.nombre)
    
class Producto(models.Model):
    nombre=models.CharField(max_length=50)
    categorias=models.ForeignKey(categoriaProd, on_delete=models.CASCADE)
    imagen=models.ImageField(upload_to="tienda", null=True, blank=True)
    precio=models.FloatField()
    disponibilidad=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    update=models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name="Producto"
        verbose_name_plural="Productos"

    def __str__(self):
        return (self.nombre)

tienda/views.py
from django.shortcuts import render
from .models import Producto

# Create your views here.

def tienda (request):
    productos=Producto.objects.all()

    return render(request, 'tienda/tienda.html', {"productos":productos})

tienda/templates/carrocompra/widget.html
    <table class="table table-bordered" style="color: beige;">

        <thead>
            <tr>
                <td colspan="3" style="color: beige; text-align: center;">Carro Compras</td>
            </tr>
          
            <tr>
             <th>Producto</th>
             <th>Cantidad</th>
             <th>Suma</th>
            </tr>

        </thead>
          
        <tbody>

            {% if request.session.carro.items %}
                {% for key, value in request.session.carro.items %}

                    <tr class="text-center"></tr>

                        <td>{{value.nombre}}</td>
                        <td>{{value.cantidad}}</td>
                        
                        
                        <td>
                            
                            <a href= "{% url 'carro:agregar' value.producto_id %}" class="btn btn-sm btn-success">+</a>
                            <a href= "{% url 'carro:restar' value.producto_id %}" class="btn btn-sm btn-success">-</a><br/>
                            ${{value.precio}} 



                        </td>


                {% endfor %}
            
            {% else %}

                <tr>
            
                    <td colspan="3" ></td>
                        <div class="alert alert-danger text-center"> 
                            Sin productos
                        </div>
                </tr>
                
            {% endif %}

        </tbody>

        <tfoot>
            <tr>
                <td colspan="3">

                    total: $ {{importe_total_carro}} 

                </td>
            </tr>

            {%if request.session.carro.items %}
            <tr>
                <td colspan="3" style="text-align: center;">

                    <a href="../pedidos" class="btn btn-success" > Hacer Pedido</a>

                </td>
            
            </tr>

            {% endif %}

        </tfoot>
    </table>